05_Trang_10_Hai_FinalProject/Models/Customer.cs
using _05_Trang_10_Hai_FinalProject.EnumValue;
using System.ComponentModel.DataAnnotations.Schema;

namespace _05_Trang_10_Hai_FinalProject.Models;

public partial class Customer
{
    [Column("id")]
    public int Id { get; set; }

    [Column("name")]
    public string? Name { get; set; }

    [Column("address")]
    public string? Address { get; set; }

    [Column("phone")]
    public int? Phone { get; set; }

    [Column("email")]
    public string? Email { get; set; }

    [Column("note")]
    public string? Note { get; set; }

    [Column("contract_date")]
    public DateTime? ContractDate { get; set; }

    [Column("type")]
    public CustomerType? Type { get; set; }

    [Column("created_by")]
    public int? CreatedBy { get; set; }

    [Column("created_at")]
    public DateTime? CreatedAt { get; set; }

    [Column("update_at")]
    public DateTime? UpdateAt { get; set; }

    [Column("update_by")]
    public int? UpdateBy { get; set; }

    public virtual User CreatedByNavigation { get; set; }

    public virtual ICollection<Export> Exports { get; set; } = new List<Export>();

    public virtual ICollection<Import> Imports { get; set; } = new List<Import>();

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();

    public virtual User UpdateByNavigation { get; set; }
}

05_Trang_10_Hai_FinalProject/Controllers/CustomersController.cs
using _05_Trang_10_Hai_FinalProject.Data;
using _05_Trang_10_Hai_FinalProject.EnumValue;
using _05_Trang_10_Hai_FinalProject.Models;
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace _05_Trang_10_Hai_FinalProject.Controllers
{
    [Authorize(Roles = $"{nameof(UserRole.ADMIN)},{nameof(UserRole.SALER)}")]
    public class CustomersController : Controller
    {
        private readonly string nameidentifier = "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier";
        private readonly Context _context;
        private readonly INotyfService _notyf;

        public CustomersController(Context context, INotyfService notyf)
        {
            _context = context;
            _notyf = notyf;
        }

        // GET: Customers
        public async Task<IActionResult> Index(string? CustomerName, string? CustomerPhone, string? CustomerEmail, string? CustomerContractDate)
        {

            if (_context.Customers == null)
            {
                return Problem("Entity set 'Context.Customer'  is null.");
            }

            var customer = await _context.Customers.Include(c => c.UpdateByNavigation).Include(c => c.CreatedByNavigation).ToListAsync();

            if (CustomerName != null)
            {
                customer = customer.Where(c => c.Name.Contains(CustomerName)).ToList();
            }
            if (CustomerPhone != null)
            {
                customer = customer.Where(c => c.Phone.ToString().Contains(CustomerPhone)).ToList();
            }
            if (CustomerEmail != null)
            {
                customer = customer.Where(c => c.Email.Contains(CustomerEmail)).ToList();
            }

            if (CustomerContractDate != null)
            {
                string createStartDate = CustomerContractDate.Split('-')[0].Trim();
                string createEndDate = CustomerContractDate.Split('-')[1].Trim();
                DateTime StartDate = new DateTime(int.Parse(createStartDate.Split("/")[2]), int.Parse(createStartDate.Split("/")[1]), int.Parse(createStartDate.Split("/")[0]));
                DateTime EndDate = new DateTime(int.Parse(createEndDate.Split("/")[2]), int.Parse(createEndDate.Split("/")[1]), int.Parse(createEndDate.Split("/")[0]));
                customer = customer.Where(c => c.ContractDate >= StartDate && c.ContractDate <= EndDate).ToList();
            }

            if (!User.IsInRole(nameof(UserRole.ADMIN)))
            {
                customer.RemoveAll(c => c.CreatedBy != int.Parse(User.FindFirst(nameidentifier).Value));
            }

            return View(customer);
        }

        // GET: Customers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Customers == null)
            {
                _notyf.Error("Somthing when wrong");
                return RedirectToAction(nameof(Index));
            }

            var customer = await _context.Customers.Include(c => c.UpdateByNavigation).Include(c => c.CreatedByNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (customer == null)
            {
                _notyf.Warning("User not exist");
                return RedirectToAction(nameof(Index));
            }

            return View(customer);
        }

        // GET: Customers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Customers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Address,Phone,Email,Note,Type")] Customer customer)
        {
            customer.CreatedBy = int.Parse(User.FindFirst(nameidentifier).Value);
            customer.UpdateBy = int.Parse(User.FindFirst(nameidentifier).Value);
            customer.CreatedAt = DateTime.Now;
            customer.UpdateAt = DateTime.Now;
            customer.ContractDate = DateTime.Now;
            _context.Add(customer);
            _notyf.Success("Customer create succeed");
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        // GET: Customers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Customers == null)
            {
                _notyf.Error("Somthing when wrong");
                return RedirectToAction(nameof(Index));
            }

            var customer = await _context.Customers.Include(c => c.UpdateByNavigation).Include(c => c.CreatedByNavigation).FirstOrDefaultAsync(c=>c.Id == id);
            if (customer == null)
            {
                _notyf.Warning("Customer not exist");
                return RedirectToAction(nameof(Index));
            }
            return View(customer);
        }

        // POST: Customers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Address,Phone,Email,Note,Type")] Customer customer)
        {
            if (id != customer.Id)
            {
                _notyf.Error("Somthing when wrong");
                return View(customer);
            }

            var oldCustomer = await _context.Customers.FindAsync(customer.Id);
            if (oldCustomer == null)
            {
                _notyf.Warning("Customer not exist");
                return View(customer);
            }
            try
            {
                oldCustomer.Name = customer.Name;
                oldCustomer.Address = customer.Address;
                oldCustomer.Phone = customer.Phone;
                oldCustomer.Email = customer.Email;
                oldCustomer.Note = customer.Note;
                oldCustomer.Type = customer.Type;
                oldCustomer.UpdateBy = int.Parse(User.FindFirst(nameidentifier).Value);
                oldCustomer.UpdateAt = DateTime.Now;
                _context.Update(oldCustomer);
                await _context.SaveChangesAsync();
                _notyf.Success("Update Success");
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!CustomerExists(customer.Id))
                {
                    _notyf.Warning("Customer not exist");
                    return View(customer);
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));
        }

        // GET: Customers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Customers == null)
            {
                return NotFound();
            }

            var customer = await _context.Customers.Include(c => c.UpdateByNavigation).Include(c => c.CreatedByNavigation)  
                .FirstOrDefaultAsync(m => m.Id == id);
            if (customer == null)
            {
                return NotFound();
            }

            return View(customer);
        }

        // POST: Customers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Customers == null)
            {
                return Problem("Entity set 'Context.Customer'  is null.");
            }
            var customer = await _context.Customers.FindAsync(id);
            if (customer != null)
            {
                _context.Customers.Remove(customer);
                await _context.SaveChangesAsync();
                _notyf.Success("Remove customer succeed!!");
            }
            else
            {
                _notyf.Warning("Customer not exist");
                return RedirectToAction(nameof(Index));
            }
            return RedirectToAction(nameof(Index));
        }

        private bool CustomerExists(int id)
        {
            return (_context.Customers?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

05_Trang_10_Hai_FinalProject/Views/Customers/Create.cshtml
@model _05_Trang_10_Hai_FinalProject.Models.Customer

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Customer</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <select asp-for="Type" asp-items="Html.GetEnumSelectList<CustomerType>()" class="form-control"></select>
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Note" class="control-label"></label>
                <textarea asp-for="Note" class="form-control"></textarea>
                <span asp-validation-for="Note" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

05_Trang_10_Hai_FinalProject/Views/Customers/Delete.cshtml
@model _05_Trang_10_Hai_FinalProject.Models.Customer

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Customer</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Phone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Note)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Note)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ContractDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ContractDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Type)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UpdateAt)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UpdateAt)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UpdateBy)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UpdateBy)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

05_Trang_10_Hai_FinalProject/Views/Customers/Details.cshtml
@model _05_Trang_10_Hai_FinalProject.Models.Customer

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Customer</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Phone)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Note)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Note)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ContractDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ContractDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Type)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CreatedByNavigation.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.UpdateAt)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.UpdateAt)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.UpdateBy)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.UpdateByNavigation.Name)
        </dd>
    </dl>
</div>
<div>
    <a class="btn btn-info" asp-action="Index">Back to List</a>
    <a class="btn btn-primary" asp-action="Edit" asp-route-id="@Model?.Id">Edit</a>
</div>

05_Trang_10_Hai_FinalProject/Views/Customers/Edit.cshtml
@model _05_Trang_10_Hai_FinalProject.Models.Customer

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Customer</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <select asp-for="Type" asp-items="Html.GetEnumSelectList<CustomerType>()" class="form-control"></select>
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Note" class="control-label"></label>
                <textarea asp-for="Note" class="form-control"></textarea>
                <span asp-validation-for="Note" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

05_Trang_10_Hai_FinalProject/Views/Customers/Index.cshtml
@model IEnumerable<_05_Trang_10_Hai_FinalProject.Models.Customer>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>

<form asp-controller="Customers" asp-action="Index" method="get">
    <p>
        Customer Name:&nbsp;<input type="text" name="CustomerName" />&nbsp;&nbsp;
        Phone:&nbsp;<input type="text" name="CustomerPhone" />&nbsp;&nbsp;
        Email:&nbsp;<input type="text" name="CustomerEmail" />&nbsp;&nbsp;
        Contract Date:&nbsp;<input type="text" name="CustomerContractDate" value="" />&nbsp;&nbsp;
        <input type="submit" value="Search" />&nbsp;
        <input type="button" onclick="location.href='@Url.Action("Index", "Customers")'" value="Clear" />
    </p>
</form>

<table class="table table-hover">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Phone)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Note)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ContractDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Type)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreatedBy)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreatedAt)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UpdateAt)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UpdateBy)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            var phone = "0" + item.Phone.ToString();
            <tr data-id="@item.Id">
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Address)
                </td>
                <td>
                    @phone
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Note)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ContractDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Type)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CreatedByNavigation.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CreatedAt)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UpdateAt)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UpdateByNavigation.Name)
                </td>
                @if (User.IsInRole(nameof(UserRole.ADMIN)))
                {
                    <td>
                        <div class="btn-group" role="group">
                            <a class="btn btn-light" asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                            <button type="button" id="toastbtnDelete" class="btn btn-light" data-item-id="@item.Id" data-item-name="@item.Name">Delete</button>
                        </div>
                    </td>
                }
            </tr>
        }
    </tbody>
</table>
<script>
    document.addEventListener("DOMContentLoaded", function () {
        var tds = document.querySelectorAll('table tr td:not(:last-child)');
        tds.forEach(function (td) {
            td.addEventListener("click", function () {
                var parentTR = this.parentElement;
                var id = parentTR.getAttribute('data-id');
                var url = '@Url.Action("Details", "Customers", new { id = -1 })';
                url = url.replace("-1", id);
                window.location.href = url;
            });
        });
    });
</script>