05_Trang_10_Hai_FinalProject/Models/Import.cs
using _05_Trang_10_Hai_FinalProject.EnumValue;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;

namespace _05_Trang_10_Hai_FinalProject.Models;

public partial class Import
{
    [Column("id")]
    public int Id { get; set; }

    [Column("code")]
    public string? Code { get; set; }

    [Column("status")]
    public ProductStatus? Status { get; set; }

    [Column("created_at")]
    public DateTime? CreatedAt { get; set; }

    [Column("created_by")]
    public int? CreatedBy { get; set; }

    [Column("update_by")]
    public int? UpdateBy { get; set; }

    [Column("update_at")]
    public DateTime? UpdateAt { get; set; }

    [Column("customer_id"), DisplayName("Customer")]
    public int? CustomerId { get; set; }

    public virtual User CreatedByNavigation { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual List<ImportInfo> ImportInfos { get; set; }

    public virtual User UpdateByNavigation { get; set; }
}

05_Trang_10_Hai_FinalProject/Controllers/ImportsController.cs
using _05_Trang_10_Hai_FinalProject.Data;
using _05_Trang_10_Hai_FinalProject.EnumValue;
using _05_Trang_10_Hai_FinalProject.Models;
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace _05_Trang_10_Hai_FinalProject.Controllers
{
    [Authorize]
    public class ImportsController : Controller
    {
        private readonly string nameidentifier = "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier";
        private readonly Context _context;
        private readonly INotyfService _notyf;

        public ImportsController(Context context, INotyfService notyf)
        {
            _context = context;
            _notyf = notyf;
        }

        public async Task<IActionResult> Index(DateTime? startCreatedAt, DateTime? endCreatedAt,
            DateTime? startUpdatedAt, DateTime? endUpdatedAt)
        {
            if (_context.Imports == null)
            {
                return Problem("Entity set 'Context.Import'  is null.");
            }

            var context = _context.Imports.Include(i => i.Customer).Include(i => i.UpdateByNavigation).Include(i => i.CreatedByNavigation);
            var import = await context.ToListAsync();

            if (startCreatedAt != null)
            {
                import = import.Where(i => i.CreatedAt >= startCreatedAt).ToList();
            }

            if (endCreatedAt != null)
            {
                import = import.Where(i => i.CreatedAt <= endCreatedAt).ToList();
            }

            if (startUpdatedAt != null)
            {
                import = import.Where(i => i.UpdateAt >= startUpdatedAt).ToList();
            }

            if (endUpdatedAt != null)
            {
                import = import.Where(i => i.UpdateAt <= endUpdatedAt).ToList();
            }

            return View(import);

        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Imports == null)
            {
                return NotFound();
            }

            var import = await _context.Imports.Include(i => i.ImportInfos).ThenInclude(i => i.Product).Include(i => i.Customer)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (import == null)
            {
                return NotFound();
            }

            ViewData["Customers"] = new SelectList(_context.Customers.Where(c => c.Products.Count() > 0), "Id", "Name");
            ViewData["Products"] = new SelectList(_context.Products, "Id", "Name");
            return View(import);
        }

        [Authorize(Roles = $"{nameof(UserRole.ADMIN)},{nameof(UserRole.WAREHOUSE_MANGEMENT)}")]
        public IActionResult Create()
        {
            Import import = new Import();
            import.ImportInfos = new List<ImportInfo>();
            import.ImportInfos.Add(new ImportInfo());
            ViewData["Customers"] = new SelectList(_context.Customers.Where(c => c.Products.Count() > 0), "Id", "Name");
            return View("Create", import);
        }

        [HttpPost]
        public IActionResult GetCusProduct(int cusId)
        {
            var res = _context.Products.Where(p => p.CustomerId == cusId);
            return Ok(res);
        }

        [HttpPost]
        public IActionResult GetProductType(int poId)
        {
            var res = _context.Products.Find(poId);
            return Ok(res);
        }

        [Authorize(Roles = $"{nameof(UserRole.ADMIN)},{nameof(UserRole.WAREHOUSE_MANGEMENT)}")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Import import)
        {
            import.CreatedBy = int.Parse(User.FindFirst(nameidentifier).Value);
            import.UpdateBy = int.Parse(User.FindFirst(nameidentifier).Value);
            import.UpdateAt = DateTime.Now;
            import.CreatedAt = DateTime.Now;

            _context.Add(import);
            await _context.SaveChangesAsync();
            _notyf.Success("Create import succeed");
            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = $"{nameof(UserRole.ADMIN)},{nameof(UserRole.WAREHOUSE_MANGEMENT)}")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Imports == null)
            {
                _notyf.Error("Something went wrong");
                return RedirectToAction(nameof(Index));
            }

            var import = await _context.Imports.Include(i => i.ImportInfos).ThenInclude(i => i.Product).Include(i => i.Customer)
                .FirstOrDefaultAsync(m => m.Id == id);
            ViewData["Customers"] = new SelectList(_context.Customers.Where(c => c.Products.Count() > 0), "Id", "Name");
            ViewData["Products"] = new SelectList(_context.Products.Where(p => p.CustomerId == import.CustomerId), "Id", "Name");
            if (import == null)
            {
                _notyf.Warning("Import not exist");
                return RedirectToAction(nameof(Index));
            }
            return View(import);
        }

        [Authorize(Roles = $"{nameof(UserRole.ADMIN)},{nameof(UserRole.WAREHOUSE_MANGEMENT)}")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Import import)
        {
            if (id != import.Id)
            {
                _notyf.Warning("Import not exist");
                return RedirectToAction(nameof(Index));
            }

            var oldImport = await _context.Imports
                            .FirstOrDefaultAsync(m => m.Id == id);
            if (oldImport == null)
            {
                _notyf.Warning("Import not exist");
                return RedirectToAction(nameof(Index));
            }
            oldImport.UpdateBy = int.Parse(User.FindFirst(nameidentifier).Value);
            oldImport.UpdateAt = DateTime.Now;
            oldImport.Status = import.Status;
            oldImport.CustomerId = import.CustomerId;
            oldImport.ImportInfos = import.ImportInfos;
            try
            {
                _context.Update(oldImport);
                _notyf.Success("Update succeed");
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!ImportExists(import.Id))
                {
                    _notyf.Warning("Import not exist");
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));

        }

        [Authorize(Roles = $"{nameof(UserRole.ADMIN)},{nameof(UserRole.WAREHOUSE_MANGEMENT)}")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Imports == null)
            {
                return NotFound();
            }

            var import = await _context.Imports
                .FirstOrDefaultAsync(m => m.Id == id);
            if (import == null)
            {
                return NotFound();
            }

            return View(import);
        }

        [Authorize(Roles = $"{nameof(UserRole.ADMIN)},{nameof(UserRole.WAREHOUSE_MANGEMENT)}")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Imports == null)
            {
                _notyf.Error("Something went wrong");
                return RedirectToAction(nameof(Index));
            }
            var import = await _context.Imports.FindAsync(id);
            if (import != null)
            {
                _context.Imports.Remove(import);
            }
            else
            {
                _notyf.Warning("Import not exist");
                return RedirectToAction(nameof(Index));
            }
            _notyf.Success("Delete succeed");
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = $"{nameof(UserRole.ADMIN)},{nameof(UserRole.WAREHOUSE_MANGEMENT)}")]
        public async Task<IActionResult> Active(int? id)
        {
            if (_context.Imports == null)
            {
                _notyf.Error("Something went wrong");
                return RedirectToAction(nameof(Index));
            }
            var import = await _context.Imports
                .FirstOrDefaultAsync(i => i.Id == id);
            if (import == null)
            {
                _notyf.Warning("Import not exist");
                return RedirectToAction(nameof(Index));

            }
            import.Status = EnumValue.ProductStatus.ACTIVE;
            import.UpdateBy = int.Parse(User.FindFirst(nameidentifier).Value);
            import.UpdateAt = DateTime.Now;
            try
            {
                _context.Update(import);
                await _context.SaveChangesAsync();
                _notyf.Success("Active Import succeed!");
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!ImportExists(import.Id))
                {
                    _notyf.Warning("Import not exist");
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = $"{nameof(UserRole.ADMIN)},{nameof(UserRole.WAREHOUSE_MANGEMENT)}")]
        public async Task<IActionResult> Deactive(int? id)
        {
            if (_context.Imports == null)
            {
                _notyf.Warning("Something went wrong");
                return RedirectToAction(nameof(Index));
            }

05_Trang_10_Hai_FinalProject/Views/Imports/Create.cshtml
@model _05_Trang_10_Hai_FinalProject.Models.Import

@{
    ViewData["Title"] = "Create";
    var code = "IP" + DateTime.Now.ToString("dd/MM/yy HH:mm:ss").Replace("/", "").Replace(" ", "").Replace(":", "");
}
<h1>Create</h1>

<h4>Import</h4>
<hr />
<div class="row">
    <form asp-action="Create" id="import_form_infor">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="row">
            <div class="form-group col-md-4">
                <label asp-for="Code" class="control-label"></label>
                <input asp-for="Code" class="form-control" value="@code" style="pointer-events: none;background-color:rgb(220,220,220)" />
                <span asp-validation-for="Code" class="text-danger"></span>
            </div>
            <div class="form-group col-md-4">
                <label asp-for="CustomerId" class="control-label"></label>
                <select asp-for="CustomerId" id="dropdownCustomer" class="form-control" asp-items="ViewBag.Customers"><option></option></select>
                <span asp-validation-for="CustomerId" class="text-danger"></span>
            </div>
            <div class="form-group col-md-4">
                <label asp-for="Status" class="control-label"></label>
                <select asp-for="Status" class="form-control" asp-items="@Html.GetEnumSelectList<ProductStatus>()"></select>
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="row" style="border">
                <table class="table" id="CodesTable" style="display:none">
                    <thead>
                        <tr>
                            <th>
                                Product Name
                            </th>
                            <th>
                                Quantity
                            </th>
                            <th>
                                Unit
                            </th>
                            <th>
                                In Pirce
                            </th>
                            <th>
                                Out Pirce
                            </th>
                            <th style="width:60px;">
                                <button id="btnAddDetailRow" type="button" class="btn btn-sm btn-secondary visible" onclick="AddItem(this)">
                                    Add
                                </button>
                            </th>
                        </tr>
                    </thead>
                    <tbody id="importInfoList">
                        @for (int i = 0; i < Model.ImportInfos.Count; i++)
                        {
                            <tr>
                                <td>
                                    <select asp-for="@Model.ImportInfos[i].ProductId" id="productCusList" class="form-control"><option></option></select>
                                    <span asp-validation-for="@Model.ImportInfos[i].ProductId" class="text-danger"></span>
                                </td>
                                <td>
                                    <input asp-for="@Model.ImportInfos[i].Count" class="form-control" />
                                    <span asp-validation-for="@Model.ImportInfos[i].Count" class="text-danger"></span>
                                </td>
                                <td>
                                    <select id="item_Product_UnitId" asp-items="Html.GetEnumSelectList<ProductUnit>()" class="form-control" style="pointer-events: none;background-color:rgb(220,220,220)">
                                        <option></option>
                                    </select>
                                </td>
                                <td>
                                    <input id="ImportInfos__InPrice" asp-for="@Model.ImportInfos[i].InPrice" class="form-control" />
                                    <span asp-validation-for="@Model.ImportInfos[i].InPrice" class="text-danger"></span>
                                </td>
                                <td>
                                    <input id="ImportInfos__OutPrice" asp-for="@Model.ImportInfos[i].OutPrice" class="form-control" style="pointer-events: none;background-color:rgb(220,220,220)" />
                                    <span asp-validation-for="@Model.ImportInfos[i].OutPrice" class="text-danger"></span>
                                </td>
                                <td style="width: 60px;">
                                    <button id='btnremove-ei' type="button" class="btn btn-sm btn-danger visible" onclick="DeleteItem(this)">
                                        Delete
                                    </button>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>

        </div>
        <div class="form-group">
            <input type="submit" value="Create" class="btn btn-primary" />
        </div>
    </form>
</div>

<div>
    <a class="btn btn-info" asp-action="Index">Back to List</a>
</div>

05_Trang_10_Hai_FinalProject/Views/Imports/Delete.cshtml
@model _05_Trang_10_Hai_FinalProject.Models.Import

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Import</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UpdateBy)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UpdateBy)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UpdateAt)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UpdateAt)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

05_Trang_10_Hai_FinalProject/Views/Imports/Details.cshtml
@model _05_Trang_10_Hai_FinalProject.Models.Import

@{
    ViewData["Title"] = "Create";
}
<h1>Detail</h1>

<h4>Import</h4>
<hr />
<div class="row">
    <div class="row">
        <div class="form-group col-md-4">
            <label asp-for="Code" class="control-label"></label>
            <input asp-for="Code" class="form-control" style="pointer-events: none;background-color:rgb(220,220,220)" />
        </div>
        <div class="form-group col-md-4">
            <label asp-for="CustomerId" class="control-label"></label>
            <select asp-for="CustomerId" id="dropdownCustomer" class="form-control" asp-items="ViewBag.Customers" style="pointer-events: none;background-color:rgb(220,220,220)"></select>
        </div>
        <div class="form-group col-md-4">
            <label asp-for="Status" class="control-label"></label>
            <select asp-for="Status" class="form-control" asp-items="@Html.GetEnumSelectList<ProductStatus>()" style="pointer-events: none;background-color:rgb(220,220,220)"></select>
        </div>
        <div class="row" style="border">
            <table class="table">
                <thead>
                    <tr>
                        <th>
                            Product Name
                        </th>
                        <th>
                            Quantity
                        </th>
                        <th>
                            Unit
                        </th>
                        <th>
                            In Pirce
                        </th>
                        <th>
                            Out Pirce
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @for (int i = 0; i < Model.ImportInfos.Count; i++)
                    {
                        <tr>
                            <td>
                                <select asp-for="@Model.ImportInfos[i].ProductId" asp-items="ViewBag.Products" class="form-control" style="pointer-events: none;background-color:rgb(220,220,220)"></select>
                            </td>
                            <td>
                                <input asp-for="@Model.ImportInfos[i].Count" class="form-control" style="pointer-events: none;background-color:rgb(220,220,220)" />
                            </td>
                            <td>
                                <select asp-items="Html.GetEnumSelectList<ProductUnit>()" class="form-control" style="pointer-events: none;background-color:rgb(220,220,220)">
                                    <option>@Model.ImportInfos[i].Product.UnitId</option>
                                </select>
                            </td>
                            <td>
                                <input asp-for="@Model.ImportInfos[i].InPrice" class="form-control" style="pointer-events: none;background-color:rgb(220,220,220)" />
                            </td>
                            <td>
                                <input asp-for="@Model.ImportInfos[i].OutPrice" class="form-control" style="pointer-events: none;background-color:rgb(220,220,220)" />
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

<div>
    <a class="btn btn-info" asp-action="Index">Back to List</a>
</div>

05_Trang_10_Hai_FinalProject/Views/Imports/Edit.cshtml
@model _05_Trang_10_Hai_FinalProject.Models.Import

@{
    ViewData["Title"] = "Create";
    var code = "IO" + DateTime.Now.ToString("yy-MM-dd H:mm:ss").Replace("-", "").Replace(":", "").Replace(" ", "");
}
<h1>Create</h1>

<h4>Import</h4>
<hr />
<div class="row">
    <form asp-action="Edit" id="import_form_infor">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="Id" />
        <div class="row">
            <div class="form-group col-md-4">
                <label asp-for="Code" class="control-label"></label>
                <input asp-for="Code" class="form-control" value="@code" style="pointer-events: none;background-color:rgb(220,220,220)" />
                <span asp-validation-for="Code" class="text-danger"></span>
            </div>
            <div class="form-group col-md-4">
                <label asp-for="CustomerId" class="control-label"></label>
                <select asp-for="CustomerId" id="dropdownCustomer" class="form-control" asp-items="ViewBag.Customers"><option></option></select>
                <span asp-validation-for="CustomerId" class="text-danger"></span>
            </div>
            <div class="form-group col-md-4">
                <label asp-for="Status" class="control-label"></label>
                <select asp-for="Status" class="form-control" asp-items="@Html.GetEnumSelectList<ProductStatus>()"></select>
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="row" style="border">
                <table class="table" id="CodesTable">
                    <thead>
                        <tr>
                            <th>
                                Product Name
                            </th>
                            <th>
                                Quantity
                            </th>
                            <th>
                                Unit
                            </th>
                            <th>
                                In Pirce
                            </th>
                            <th>
                                Out Pirce
                            </th>
                        </tr>
                    </thead>
                    <tbody id="importInfoList">
                        @for (int i = 0; i < Model.ImportInfos.Count; i++)
                        {
                            <input type="hidden" asp-for="@Model.ImportInfos[i].Id" />
                            <tr>
                                <td>
                                    <select asp-for="@Model.ImportInfos[i].ProductId" id="productCusList" class="form-control" asp-items="ViewBag.Products"><option></option></select>
                                    <span asp-validation-for="@Model.ImportInfos[i].ProductId" class="text-danger"></span>
                                </td>
                                <td>
                                    <input asp-for="@Model.ImportInfos[i].Count" class="form-control" />
                                    <span asp-validation-for="@Model.ImportInfos[i].ProductId" class="text-danger"></span>
                                </td>
                                <td>
                                    <select id="item_Product_UnitId" asp-items="Html.GetEnumSelectList<ProductUnit>()" class="form-control" style="pointer-events: none;background-color:rgb(220,220,220)">
                                        <option>@Model.ImportInfos[i].Product.UnitId</option>
                                    </select>
                                </td>
                                <td>
                                    <input id="ImportInfos__InPrice" asp-for="@Model.ImportInfos[i].InPrice" class="form-control" />
                                    <span asp-validation-for="@Model.ImportInfos[i].InPrice" class="text-danger"></span>
                                </td>
                                <td>
                                    <input id="ImportInfos__OutPrice" asp-for="@Model.ImportInfos[i].OutPrice" class="form-control" style="pointer-events: none;background-color:rgb(220,220,220)" />
                                    <span asp-validation-for="@Model.ImportInfos[i].OutPrice" class="text-danger"></span>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>

        </div>
        <div class="form-group">
            <input type="submit" value="Save" class="btn btn-primary" />
        </div>
    </form>
</div>

<div>
    <a class="btn btn-info" asp-action="Index">Back to List</a>
</div>

05_Trang_10_Hai_FinalProject/Views/Imports/Index.cshtml
@model IEnumerable<_05_Trang_10_Hai_FinalProject.Models.Import>

@{
    ViewData["Title"] = "Index";
    var stt = 1;
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>

<form asp-controller="Imports" asp-action="Index" method="get">
    <p>
        Start Created At: <input type="date" name="startCreatedAt" id="startCreatedAt" />
        End Created At: <input type="date" name="endCreatedAt" id="endCreatedAt" />
    </p>

    <p>
        Start Updated At: <input type="date" name="startUpdatedAt" id="startUpdatedAt" />
        End Updated At: <input type="date" name="endUpdatedAt" id="endUpdatedAt" />
    </p>

    <p>
        <input type="submit" value="Search" />
        <button><a href="/Imports">Clear</a></button>
    </p>
</form>


<table class="table table-hover">
    <thead>
        <tr>
            <th>
                STT
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Code)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Customer.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreatedBy)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreatedAt)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UpdateBy)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UpdateAt)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr data-id="@item.Id">
                <td>
                    @stt
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Code)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Customer.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CreatedByNavigation.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CreatedAt)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UpdateByNavigation.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UpdateAt)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Status)
                </td>
                @if (User.IsInRole(nameof(UserRole.ADMIN)) || User.IsInRole(nameof(UserRole.WAREHOUSE_MANGEMENT)))
                {
                    <td>
                        <div class="btn-group" role="group">
                            <a class="btn btn-light" asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                            @{
                                if (item.Status == ProductStatus.ACTIVE)
                                {
                                    <a class="btn btn-light" asp-action="Deactive" asp-route-id="@item.Id">Deactive</a>
                                }
                                else
                                {
                                    <a class="btn btn-light" asp-action="Active" asp-route-id="@item.Id">Active</a>
                                }
                            }
                        </div>
                    </td>
                }
            </tr>
            stt++;
        }
    </tbody>
</table>
<script>
    document.addEventListener("DOMContentLoaded", function () {
        var tds = document.querySelectorAll('table tr td:not(:last-child)');
        tds.forEach(function (td) {
            td.addEventListener("click", function () {
                var parentTR = this.parentElement;
                var id = parentTR.getAttribute('data-id');
                var url = '@Url.Action("Details", "Imports", new { id = -1 })';
                url = url.replace("-1", id);
                window.location.href = url;
            });
        });
    });
</script>