05_Trang_10_Hai_FinalProject/Controllers/ProductsController.cs
using _05_Trang_10_Hai_FinalProject.Data;
using _05_Trang_10_Hai_FinalProject.EnumValue;
using _05_Trang_10_Hai_FinalProject.Models;
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace _05_Trang_10_Hai_FinalProject.Controllers
{
    [Authorize]
    public class ProductsController : Controller
    {
        private readonly Context _context;
        private readonly INotyfService _notyf;

        public ProductsController(Context context, INotyfService notyf)
        {
            _context = context;
            _notyf = notyf;
        }

        public async Task<IActionResult> Index(string? ProductsName, string? CustomerName, int? ProductsCategory)
        {
            var context = _context.Products.Include(p => p.Category).Include(p => p.Customer);

            var products = await context.ToListAsync();
            ViewData["Category"] = new SelectList(_context.Categories, "Id", "Name");
            if (ProductsName != null)
            {
                products = products.Where(c => c.Name.ToLower().Contains(ProductsName.ToLower())).ToList();
            }
            if (CustomerName != null)
            {
                products = products.Where(c => c.Customer.Name.ToLower().Contains(CustomerName.ToLower())).ToList();
            }
            if (ProductsCategory != null && ProductsCategory != -1)
            {
                products = products.Where(c => c.CategoryId == ProductsCategory).ToList();
            }

            return View(products);
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Products == null)
            {
                _notyf.Error("Somthing when wrong");
                return RedirectToAction(nameof(Index));
            }

            var product = await _context.Products
                .Include(p => p.Category)
                .Include(p => p.Customer)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (product == null)
            {
                _notyf.Warning("Product not exist");
                return RedirectToAction(nameof(Index));
            }

            return View(product);
        }

        [Authorize(Roles = $"{nameof(UserRole.ADMIN)},{nameof(UserRole.WAREHOUSE_MANGEMENT)}")]
        public IActionResult Create()
        {
            ViewData["Category"] = new SelectList(_context.Categories, "Id", "Name");
            ViewData["Customer"] = new SelectList(_context.Customers, "Id", "Name");
            return View();
        }

        [Authorize(Roles = $"{nameof(UserRole.ADMIN)},{nameof(UserRole.WAREHOUSE_MANGEMENT)}")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,CategoryId,UnitId,CustomerId,Status")] Product product)
        {
            if (ModelState.IsValid)
            {
                _context.Add(product);
                _notyf.Success("Product create succeed");
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name", product.CategoryId);
            ViewData["CustomerId"] = new SelectList(_context.Customers, "Id", "Name", product.CustomerId);
            return View(product);
        }

        [Authorize(Roles = $"{nameof(UserRole.ADMIN)},{nameof(UserRole.WAREHOUSE_MANGEMENT)}")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Products == null)
            {
                _notyf.Error("Somthing when wrong");
                return RedirectToAction(nameof(Index));
            }

            var product = await _context.Products.FindAsync(id);
            if (product == null)
            {
                _notyf.Warning("Product not exist");
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name", product.CategoryId);
            ViewData["CustomerId"] = new SelectList(_context.Customers, "Id", "Name", product.CustomerId);
            return View(product);
        }

        [Authorize(Roles = $"{nameof(UserRole.ADMIN)},{nameof(UserRole.WAREHOUSE_MANGEMENT)}")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,CategoryId,UnitId,CustomerId,Status")] Product product)
        {
            if (id != product.Id)
            {
                _notyf.Error("Somthing when wrong");
                return RedirectToAction(nameof(Index));
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(product);
                    _notyf.Success("Update succeed");
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(product.Id))
                    {
                        _notyf.Error("Somthing when wrong");
                        return RedirectToAction(nameof(Index));
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Id", product.CategoryId);
            ViewData["CustomerId"] = new SelectList(_context.Customers, "Id", "Id", product.CustomerId);
            return View(product);
        }

        [Authorize(Roles = $"{nameof(UserRole.ADMIN)},{nameof(UserRole.WAREHOUSE_MANGEMENT)}")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Products == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .Include(p => p.Category)
                .Include(p => p.Customer)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        [Authorize(Roles = $"{nameof(UserRole.ADMIN)},{nameof(UserRole.WAREHOUSE_MANGEMENT)}")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Products == null)
            {
                return Problem("Entity set 'Context.Product'  is null.");
            }
            var product = await _context.Products.FindAsync(id);
            if (product != null)
            {
                _notyf.Success("Remove succeed");
                _context.Products.Remove(product);
            }
            else
            {
                _notyf.Warning("Product not exist");
                return RedirectToAction(nameof(Index));
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = $"{nameof(UserRole.ADMIN)},{nameof(UserRole.WAREHOUSE_MANGEMENT)}")]
        private bool ProductExists(int id)
        {
            return (_context.Products?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

05_Trang_10_Hai_FinalProject/Controllers/UsersController.cs
using _05_Trang_10_Hai_FinalProject.Data;
using _05_Trang_10_Hai_FinalProject.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;


namespace _05_Trang_10_Hai_FinalProject.Controllers
{
    using _05_Trang_10_Hai_FinalProject.EnumValue;
    using AspNetCoreHero.ToastNotification.Abstractions;
    using BCrypt.Net;
    using Microsoft.AspNetCore.Authorization;

    public class UsersController : Controller
    {
        private readonly string nameidentifier = "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier";
        private readonly int key = 13;
        private readonly string pass = "123";
        private readonly Context _context;
        private readonly INotyfService _notyf;

        public UsersController(Context context, INotyfService notyf)
        {
            _context = context;
            _notyf = notyf;
        }

        [Authorize(Roles = nameof(UserRole.ADMIN))]
        public async Task<IActionResult> Index(string? CreatedUserAt, string? UpdatedUserAt, string? emailUser, UserRole? roleUser)
        {
            if (_context.Users == null)
            {
                return Problem("Entity set 'Context.User'  is null.");
            }

            var cus = await _context.Users.Include(c => c.UpdateByNavigation).Include(c => c.CreatedByNavigation).ToListAsync();
            if (CreatedUserAt != null)
            {
                string createStartDate = CreatedUserAt.Split('-')[0].Trim();
                string createEndDate = CreatedUserAt.Split('-')[1].Trim();
                DateTime StartDate = new DateTime(int.Parse(createStartDate.Split("/")[2]), int.Parse(createStartDate.Split("/")[1]), int.Parse(createStartDate.Split("/")[0]));
                DateTime EndDate = new DateTime(int.Parse(createEndDate.Split("/")[2]), int.Parse(createEndDate.Split("/")[1]), int.Parse(createEndDate.Split("/")[0]));
                cus = cus.Where(c => c.CreatedAt >= StartDate && c.CreatedAt <= EndDate).ToList();
            }
            if (UpdatedUserAt != null)
            {
                string UpdatedStartDate = UpdatedUserAt.Split('-')[0].Trim();
                string UpdatedEndDate = UpdatedUserAt.Split('-')[1].Trim();
                DateTime StartDate = new DateTime(int.Parse(UpdatedStartDate.Split("/")[2]), int.Parse(UpdatedStartDate.Split("/")[1]), int.Parse(UpdatedStartDate.Split("/")[0]));
                DateTime EndDate = new DateTime(int.Parse(UpdatedEndDate.Split("/")[2]), int.Parse(UpdatedEndDate.Split("/")[1]), int.Parse(UpdatedEndDate.Split("/")[0]));
                cus = cus.Where(c => c.UpdateAt >= StartDate && c.UpdateAt <= EndDate).ToList();
            }

            if (emailUser != null)
            {
                cus = cus.Where(c => c.Email.Contains(emailUser)).ToList();
            }
            if (roleUser != null)
            {
                cus = cus.Where(c => c.Role == roleUser).ToList();
            }
            cus.RemoveAll(c => c.Id == int.Parse(User.FindFirst(nameidentifier).Value));
            return View(cus);
            //return _context.User != null ? 
            //              View(await _context.User.ToListAsync()) :
            //              Problem("Entity set 'Context.User'  is null.");
        }

        [Authorize]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Users == null)
            {
                _notyf.Error("Somthing when wrong");
                return RedirectToAction(nameof(Index));
            }

            var user = await _context.Users.Include(c => c.UpdateByNavigation).Include(c => c.CreatedByNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                _notyf.Warning("User not exist");
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        [Authorize(Roles = nameof(UserRole.ADMIN))]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = nameof(UserRole.ADMIN))]
        public async Task<IActionResult> Create([Bind("Id,Name,Email,Password,Role,Status")] User user)
        {
            var listUsers = await _context.Users.ToListAsync();
            if (listUsers.Any(u => u.Email == user.Email)){
                _notyf.Warning("Email user not exist");
                return View(user);
            }
            user.CreatedBy = int.Parse(User.FindFirst(nameidentifier).Value);
            user.UpdateBy = int.Parse(User.FindFirst(nameidentifier).Value);
            user.CreatedAt = DateTime.Now;
            user.UpdateAt = DateTime.Now;
            user.Password = BCrypt.EnhancedHashPassword(user.Password, key);
            _context.Add(user);
            await _context.SaveChangesAsync();
            _notyf.Success("Create user succeed");
            return RedirectToAction(nameof(Index));

        }

        [Authorize(Roles = nameof(UserRole.ADMIN))]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Users == null)
            {
                _notyf.Error("Somthing when wrong");
                return RedirectToAction(nameof(Index));
            }

            var user = await _context.Users.Include(c => c.UpdateByNavigation).Include(c => c.CreatedByNavigation).FirstOrDefaultAsync(u => u.Id == id);
            if (user == null)
            {
                _notyf.Warning("User not exist");
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = nameof(UserRole.ADMIN))]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Role,Email,Status")] User user)
        {
            if (id != user.Id)
            {
                _notyf.Warning("User not exist");
                return RedirectToAction(nameof(Index));
            }
            var oldUser = await _context.Users
                .FirstOrDefaultAsync(m => m.Id == id);

            if (oldUser == null)
            {
                _notyf.Warning("User not exist");
                return RedirectToAction(nameof(Index));
            }
            oldUser.Status = user.Status;
            oldUser.Role = user.Role;
            oldUser.Email = user.Email;
            oldUser.UpdateAt = DateTime.Now;
            oldUser.UpdateBy = int.Parse(User.FindFirst(nameidentifier).Value);
            try
            {
                _context.Update(oldUser);
                await _context.SaveChangesAsync();
                _notyf.Success("Update Success");
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!UserExists(user.Id))
                {
                    _notyf.Warning("User not exist");
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    throw;
                }
            }

            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = nameof(UserRole.ADMIN))]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Users == null)
            {
                return NotFound();
            }

            var user = await _context.Users
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = nameof(UserRole.ADMIN))]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Users == null)
            {
                return Problem("Entity set 'Context.User'  is null.");
            }
            var user = await _context.Users.FindAsync(id);
            if (user != null)
            {
                _context.Users.Remove(user);
                await _context.SaveChangesAsync();
                _notyf.Success("Remove user succeed!!");
            }
            else
            {
                _notyf.Warning("User not exist");
                return RedirectToAction(nameof(Index));
            }

            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = nameof(UserRole.ADMIN))]
        public async Task<IActionResult> ResetPass(int? id)
        {
            if (_context.Users == null)
            {
                return Problem("Entity set 'Context.User'  is null.");
            }
            var user = await _context.Users
                .FirstOrDefaultAsync(m => m.Id == id);
            user.Password = BCrypt.EnhancedHashPassword(pass, key);
            try
            {
                _context.Update(user);
                await _context.SaveChangesAsync();
                _notyf.Success("Reset password succeed!");
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!UserExists(user.Id))
                {
                    _notyf.Warning("User not exist");
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    throw;
                }
            }
            return Redirect($"/Users/Edit/{id}");
        }

        [Authorize(Roles = nameof(UserRole.ADMIN))]
        public async Task<IActionResult> Active(int? id)
        {
            if (_context.Users == null)
            {
                return Problem("Entity set 'Context.User'  is null.");
            }
            var user = await _context.Users
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                _notyf.Warning("User not exist");

05_Trang_10_Hai_FinalProject/Views/Shared/Forbidden.cshtml
@{
    ViewData["Title"] = "Forbidden";
}

<style>
    a {
        color: #EE4B5E !important;
        text-decoration: none;
    }

    a:hover {
        color: #FFFFFF !important;
        text-decoration: none;
     }

    .text-wrapper {
        height: 100%;
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
    }

    .title {
        font-size: 5em;
        font-weight: 700;
        color: #EE4B5E;
    }

    .subtitle {
        font-size: 40px;
        font-weight: 700;
        color: #1FA9D6;
    }

    .isi {
        font-size: 18px;
        text-align: center;
        margin: 30px;
        padding: 20px;
        color: white;
    }

    .buttons {
        margin: 30px;
        font-weight: 700;
        border: 2px solid #EE4B5E;
        text-decoration: none;
        padding: 15px;
        text-transform: uppercase;
        color: #EE4B5E;
        border-radius: 26px;
        transition: all 0.2s ease-in-out;
        display: inline-block;
    }

    .buttons:hover {
        background-color: #EE4B5E;
        color: white;
        transition: all 0.2s ease-in-out;
     }

</style>
<div class="text-wrapper">
    <div class="title" data-content="404">
        403 - ACCESS DENIED
    </div>

    <div class="subtitle">
        Oops, You don't have permission to access this page.
    </div>
    <div class="isi">
        A web server may return a 403 Forbidden HTTP status code in response to a request from a client for a web page or resource to indicate that the server can be reached and understood the request, but refuses to take any further action. Status code 403 responses are the result of the web server being configured to deny access, for some reason, to the requested resource by the client.
    </div>

    <div class="buttons">
        <a class="button" asp-controller="Home" asp-action="Index">Go to homepage</a>
    </div>
</div>

05_Trang_10_Hai_FinalProject/Views/Shared/_Dialog.cshtml
<div class="position-fixed top-50 start-50 translate-middle" style="z-index: 11">
    <div id="liveToast" class="toast div_delete hide" role="alert" aria-live="assertive" aria-atomic="true">
        <div class="toast-header">
            <strong class="me-auto">Delete</strong>
            <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
        </div>
        <div class="toast-body">
            Your sure want to <strong class="me-auto">Delete </strong><i class="item_name_delete"></i>
            <div class="mt-2 pt-2 border-top">
                <form asp-action="Delete">
                    <input type="hidden" data-val="true" id="Id" name="Id" value="">
                    <input type="submit" value="Delete" class="btn btn-danger" />&nbsp;&nbsp
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="toast">Close</button>
                </form>
            </div>
        </div>
    </div>
</div>

05_Trang_10_Hai_FinalProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - _05_Trang_10_Hai_FinalProject</title>
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/_05_Trang_10_Hai_FinalProject.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Warehouse Project</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link text-dark dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Manegement
                                </a>
                                <ul class="dropdown-menu">
                                    @if (User.IsInRole(nameof(UserRole.ADMIN)))
                                    {
                                        <li><a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Users</a></li>
                                    }
                                    @if (User.IsInRole(nameof(UserRole.ADMIN)) || User.IsInRole(nameof(UserRole.SALER)))
                                    {
                                        <li><a class="nav-link text-dark" asp-area="" asp-controller="Customers" asp-action="Index">Customers</a></li>
                                    }
                                    @if (User.IsInRole(nameof(UserRole.ADMIN)) || User.IsInRole(nameof(UserRole.SALER)))
                                    {
                                        <li><a class="nav-link text-dark" asp-area="" asp-controller="Categories" asp-action="Index">Categories</a></li>
                                    }
                                    <li><a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">Products</a></li>
                                    <li><a class="nav-link text-dark" asp-area="" asp-controller="Imports" asp-action="Index">Imports</a></li>
                                    <li><a class="nav-link text-dark" asp-area="" asp-controller="Exports" asp-action="Index">Exports</a></li>
                                </ul>
                            </li>
                        }
                    </ul>
                    <ul class="navbar-nav flex-grow-2">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Details" asp-route-id="@int.Parse(User.FindFirst("http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier").Value)">@User.Identity.Name</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="LogOut">LogOut</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Login">Login</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @if (ViewContext.RouteData.Values["controller"].ToString().ToLower() != "home")
            {
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item">
                            @Html.ActionLink("Home", "Index", "Home")
                        </li>
                        @if (@ViewContext.RouteData.Values["action"].ToString() != "Index")
                        {
                            <li class="breadcrumb-item">
                                @Html.ActionLink(ViewContext.RouteData.Values["controller"].ToString(), "Index")
                            </li>
                            <li class="breadcrumb-item active" aria-current="page">
                                @ViewContext.RouteData.Values["action"].ToString()
                            </li>
                        }
                        else
                        {
                            <li class="breadcrumb-item active" aria-current="page">
                                @ViewContext.RouteData.Values["controller"].ToString()
                            </li>
                        }
                    </ol>
                </nav>
            }
            @RenderBody()
            @Html.Partial("_Dialog")
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - _05_Trang_10_Hai_FinalProject - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

    <script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>

    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)

    @await RenderSectionAsync("Scripts", required: false)
    @await Component.InvokeAsync("Notyf")
</body>
</html>