05_Trang_10_Hai_FinalProject/Models/Category.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace _05_Trang_10_Hai_FinalProject.Models;

public partial class Category
{
    [Column("id")]
    public int Id { get; set; }

    [Column("name")]
    public string? Name { get; set; }

    [Column("note")]
    public string? Note { get; set; }

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
}

05_Trang_10_Hai_FinalProject/Controllers/CategoriesController.cs
using _05_Trang_10_Hai_FinalProject.Data;
using _05_Trang_10_Hai_FinalProject.EnumValue;
using _05_Trang_10_Hai_FinalProject.Models;
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace _05_Trang_10_Hai_FinalProject.Controllers
{
    [Authorize(Roles = $"{nameof(UserRole.ADMIN)},{nameof(UserRole.SALER)}")]
    public class CategoriesController : Controller
    {
        private readonly Context _context;
        private readonly INotyfService _notyf;

        public CategoriesController(Context context, INotyfService notyf)
        {
            _context = context;
            _notyf = notyf;
        }

        // GET: Categories
        public async Task<IActionResult> Index(string? CategoryName)
        {
            if (_context.Categories == null)
            {
                return Problem("Entity set 'Context.Category'  is null.");
            }

            var category = await _context.Categories.Include(c => c.Products).ToListAsync();

            if (CategoryName != null)
            {
                category = category.Where(c => c.Name.ToLower().Contains(CategoryName.ToLower())).ToList();
            }
            return View(category);

        }

        // GET: Categories/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Categories == null)
            {
                _notyf.Warning("Category not exist");
                return RedirectToAction(nameof(Index));
            }

            var category = await _context.Categories.Include(c => c.Products)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (category == null)
            {
                _notyf.Warning("Category not exist");
                return RedirectToAction(nameof(Index));
            }

            return View(category);
        }

        // GET: Categories/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Categories/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Note")] Category category)
        {
            _context.Add(category);
            await _context.SaveChangesAsync();
            _notyf.Success("Create category succeed");
            return RedirectToAction(nameof(Index));
        }

        // GET: Categories/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Categories == null)
            {
                _notyf.Error("Somthing when wrong");
                return RedirectToAction(nameof(Index));
            }

            var category = await _context.Categories.Include(c => c.Products).FirstOrDefaultAsync(c => c.Id == id);
            if (category == null)
            {
                _notyf.Warning("Category not exist");
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // POST: Categories/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Note")] Category category)
        {
            if (id != category.Id)
            {
                _notyf.Error("Somthing when wrong");
                return RedirectToAction(nameof(Index));
            }

            try
            {
                _context.Update(category);
                _notyf.Success("Update succeed");
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!CategoryExists(category.Id))
                {
                    _notyf.Warning("Category not exist");
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));
        }

        // GET: Categories/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Categories == null)
            {
                _notyf.Error("Somthing when wrong");
                return RedirectToAction(nameof(Index));
            }

            var category = await _context.Categories
                .FirstOrDefaultAsync(m => m.Id == id);
            if (category == null)
            {
                _notyf.Warning("Category not exist");
                return RedirectToAction(nameof(Index));
            }

            return View(category);
        }

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Categories == null)
            {
                _notyf.Error("Somthing when wrong");
                return RedirectToAction(nameof(Index));
            }
            var category = await _context.Categories.FindAsync(id);
            if (category != null)
            {
                _context.Categories.Remove(category);
                _notyf.Success("Delete succeed");
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CategoryExists(int id)
        {
            return (_context.Categories?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

05_Trang_10_Hai_FinalProject/Views/Categories/Create.cshtml
@model _05_Trang_10_Hai_FinalProject.Models.Category

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Category</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Note" class="control-label"></label>
                <input asp-for="Note" class="form-control" />
                <span asp-validation-for="Note" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

05_Trang_10_Hai_FinalProject/Views/Categories/Delete.cshtml
@model _05_Trang_10_Hai_FinalProject.Models.Category

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Category</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Note)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Note)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

05_Trang_10_Hai_FinalProject/Views/Categories/Details.cshtml
@model _05_Trang_10_Hai_FinalProject.Models.Category

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Category</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Note)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Note)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

05_Trang_10_Hai_FinalProject/Views/Categories/Edit.cshtml
@model _05_Trang_10_Hai_FinalProject.Models.Category

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Category</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Note" class="control-label"></label>
                <input asp-for="Note" class="form-control" />
                <span asp-validation-for="Note" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

05_Trang_10_Hai_FinalProject/Views/Categories/Index.cshtml
@model IEnumerable<_05_Trang_10_Hai_FinalProject.Models.Category>

@{
    ViewData["Title"] = "Index";
}
<style>

</style>
<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>

<form asp-controller="Categories" asp-action="Index" method="get">
    <p>
        Name: <input type="text" name="CategoryName" id="name" />
        <input type="submit" value="Search" />
        <input type="button" onclick="location.href='@Url.Action("Index", "Categories")'" value="Clear" />
    </p>
</form>

<table class="table table-hover">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Note)
            </th>
            <th>
                Product Quantity
            </th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr data-id="@item.Id">
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Note)
                </td>
                <td>
                    @item.Products.Count()
                </td>
                @if (User.IsInRole(nameof(UserRole.ADMIN)))
                {
                    <td class="align-middle">
                        <div class="btn-group" role="group">
                            <a class="btn btn-light" asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                            <button type="button" id="toastbtnDelete" class="btn btn-light" data-item-id="@item.Id" data-item-name="@item.Name">Delete</button>
                        </div>
                    </td>
                }
            </tr>
        }
    </tbody>
</table>

<script>
    document.addEventListener("DOMContentLoaded", function () {
        var tds = document.querySelectorAll('table tr td:not(:last-child)');
        tds.forEach(function (td) {
            td.addEventListener("click", function () {
                var parentTR = this.parentElement;
                var id = parentTR.getAttribute('data-id');
                var url = '@Url.Action("Details", "Categories", new { id = -1 })';
                url = url.replace("-1", id);
                window.location.href = url;
            });
        });
    });
</script>